using System;
using System.Collections;
using System.Collections.Generic;
using SplineMesh;
using UnityEngine;

public class WalkPath : MonoBehaviour
{
    private GameObject generated;
    private Spline spline;
    private float rate = 0;

    public GameObject Follower;
    public float DurationInSecond;
    public bool moveOnPath;

    private void OnEnable()
    {
        spline = GetComponent<Spline>(); 
        
        rate = 0;
        string generatedName = "generated by " + GetType().Name;
        var generatedTranform = transform.Find(generatedName);
        generated = generatedTranform != null ? generatedTranform.gameObject : Instantiate(Follower, gameObject.transform);
        generated.name = generatedName;
    }

    void EditorUpdate() {
        rate += Time.deltaTime / DurationInSecond;
        if (rate > spline.nodes.Count - 1) {
            rate -= spline.nodes.Count - 1;
        }
        PlaceFollower();
    }

    private void PlaceFollower()
    {
        CurveSample sample = spline.GetSample(rate);
        var worldPos = transform.TransformPoint(sample.location);
        Follower.transform.position = new Vector3(worldPos.x, worldPos.y, -1);
    }
    
   

    // Update is called once per frame
    void Update()
    {
        if(moveOnPath) EditorUpdate();
    }
}
